import Link from "next/link";
import { CheckCircle2, MessageCircle, ArrowRight, Calculator, Clock, Phone } from "lucide-react";
import type { Metadata } from "next";
import ConversionTracker from "@/components/ConversionTracker";

export const metadata: Metadata = {
  title: "Quote Request Received | Wine Press Solar Services",
  description:
    "Thank you for your solar quote request. Our team will review your system specification and contact you within 24 hours.",
  robots: { index: false, follow: false },
};

const NEXT_STEPS = [
  {
    icon: Clock,
    step: "01",
    title: "We Review Your Spec",
    desc: "Our engineers review the system specification generated by your calculator results and verify the sizing.",
  },
  {
    icon: Phone,
    step: "02",
    title: "We Call You Within 24 Hours",
    desc: "A Wine Press consultant will call your WhatsApp number to confirm details and answer any questions.",
  },
  {
    icon: CheckCircle2,
    step: "03",
    title: "You Receive a Formal Quote",
    desc: "We send a detailed, fixed-price quote by WhatsApp and email — no hidden costs, no surprises.",
  },
];

export default function ThankYouPage() {
  return (
    <main className="min-h-screen bg-background pt-32 pb-24 px-6">
      <ConversionTracker />
      <div className="max-w-3xl mx-auto">

        {/* Hero confirmation block */}
        <div className="bg-surface border-2 border-primary rounded-[8px] p-12 md:p-16 mb-12 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-primary rounded-[8px] mb-8">
            <CheckCircle2 className="w-8 h-8 text-[#1A1A1B]" />
          </div>
          <h1 className="font-display font-black text-4xl md:text-5xl text-foreground uppercase tracking-tighter mb-4">
            Quote Request Received!
          </h1>
          <p className="text-secondary-text text-lg font-medium max-w-lg mx-auto leading-relaxed">
            We have your system specification and contact details. Expect a call
            from our team on your WhatsApp number{" "}
            <span className="text-foreground font-black">within 24 hours.</span>
          </p>
        </div>

        {/* What happens next */}
        <div className="mb-12">
          <p className="text-[10px] font-black uppercase tracking-[0.3em] text-primary mb-8">
            What Happens Next
          </p>
          <div className="space-y-px border border-border">
            {NEXT_STEPS.map(({ icon: Icon, step, title, desc }) => (
              <div
                key={step}
                className="flex gap-8 items-start p-8 bg-background border-b border-border last:border-b-0"
              >
                <div className="shrink-0 flex flex-col items-center gap-2">
                  <span className="font-display font-black text-3xl text-primary leading-none tracking-tighter">
                    {step}
                  </span>
                  <Icon className="w-5 h-5 text-secondary-text" />
                </div>
                <div>
                  <h3 className="font-black text-foreground uppercase tracking-wide text-sm mb-2">
                    {title}
                  </h3>
                  <p className="text-secondary-text text-sm font-medium leading-relaxed">
                    {desc}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Can't wait? CTA */}
        <div className="bg-background border border-border rounded-[8px] p-8 mb-10 flex flex-col sm:flex-row items-center justify-between gap-6">
          <div>
            <p className="font-black text-foreground uppercase tracking-wider text-sm mb-1">
              Can't wait? Chat us now.
            </p>
            <p className="text-secondary-text text-xs font-medium">
              Our team is available Monday – Saturday, 8am – 6pm.
            </p>
          </div>
          <a
            href="https://wa.me/2349166301384"
            target="_blank"
            rel="noopener noreferrer"
            className="btn-flat btn-primary h-12 px-8 text-xs uppercase tracking-widest shrink-0"
          >
            <MessageCircle className="w-4 h-4" />
            Open WhatsApp
          </a>
        </div>

        {/* Secondary actions */}
        <div className="flex flex-col sm:flex-row gap-4">
          <Link
            href="/calculator"
            className="btn-flat btn-outline h-12 px-8 flex-1 text-xs uppercase tracking-widest"
          >
            <Calculator className="w-4 h-4" />
            Recalculate
          </Link>
          <Link
            href="/"
            className="btn-flat h-12 px-8 flex-1 text-xs uppercase tracking-widest border border-border text-secondary-text hover:text-foreground hover:bg-surface transition-colors"
          >
            Back to Home
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </main>
  );
}
